In [3]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [4]:
from torch.autograd import Variable

In [5]:
x = Variable(torch.ones(2, 2), requires_grad=True)

In [6]:
y = x.mean()

In [7]:
y

tensor(1., grad_fn=<MeanBackward1>)

In [8]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [9]:
y.backward()
x.grad

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])

In [10]:
x.data

tensor([[1., 1.],
        [1., 1.]])

In [11]:
y.grad_fn

In [12]:
if(x.grad_fn is None):
    print("it's none")

it's none


In [13]:
def get_data():
    train_X = np.asarray([float(x) + 1.5 for x in range(10)])
    train_Y = np.asarray([float(y) + 0.25 for y in range(5)])
    dtype = torch.FloatTensor
    X = Variable(torch.from_numpy(train_X).type(dtype), requires_grad=False).view(10, 1)
    y = Variable(torch.from_numpy(train_Y).type(dtype), requires_grad=False)
    return X, y

In [14]:
X, y = get_data()

In [15]:
def simple_network(x):
    y_pred = torch.matmul(x, w) + b
    return y_pred

f = torch.nn.Linear(17, 1) # simpler

In [16]:
def loss_fn(y, y_pred):
    loss = (y_pred - y).pow(2).sum()
    for param in [w, b]:
        if not param.grad is None: param.grad.data.zero_()
    loss.backward()
    return loss.data[0]

In [17]:
def optimize(learning_rate):
    w.data = w.data - learning_rate * w.grad.data
    b.data = b.data - learning_rate * b.grad.data


## Loading Data

In [18]:
# inherit from PyTorch Dataset class
from torch.utils.data import Dataset
class DogsAndCats(Dataset):
    def __init__(self, root_dir, size=(224, 224)):
        self.files = glob(root_dir)
        self.size = size
    def __len__(self):
        # return length of the dataset
        return len(self.files)
    def __getitem__(self, idx):
        # return idx item
        img = np.asarray(Image.open(self.files[idx]).resize(self.size))
        label = self.files[idx].split('/')[-2]
        return img, label

In [19]:
from torch.utils.data import DataLoader
dataloader = DataLoader(dogsdset, batch_size = 32, num_workers=32)

for imgs, labels in dataloader:
    # apply dl here
    pass

NameError: name 'dogsdset' is not defined

In [20]:
from torch.nn import Linear
nnLayer = Linear(in_features=10, out_features=5, bias=True)
nnLayer(torch.randn(1, 10))

tensor([[ 1.0453, -0.9358, -0.1077, -0.4623, -0.2436]], grad_fn=<ThAddmmBackward>)

In [21]:
nnLayer.weight

Parameter containing:
tensor([[-0.2988, -0.1713,  0.2367, -0.1571,  0.0978,  0.0972,  0.0534, -0.0600,
          0.0919,  0.2500],
        [ 0.3062, -0.0861,  0.1847,  0.2638,  0.1647, -0.2271, -0.0618, -0.2901,
          0.0367, -0.0994],
        [-0.0484, -0.2311,  0.2529, -0.0973, -0.1882,  0.0618,  0.2429,  0.1626,
         -0.0691,  0.2074],
        [ 0.0879, -0.2557,  0.1246, -0.2058, -0.1286,  0.1709, -0.0717,  0.2440,
         -0.2786, -0.2542],
        [-0.0278,  0.0763, -0.1136, -0.1299, -0.1094, -0.2322, -0.3000,  0.1631,
         -0.2127, -0.2973]], requires_grad=True)

In [22]:
nnLayer.bias

Parameter containing:
tensor([ 0.2534, -0.0291,  0.0410,  0.1434,  0.2672], requires_grad=True)

In [23]:
L1 = Linear(10, 5)
L2 = Linear(5, 2)
L2(L1(torch.randn(1, 10)))

tensor([[0.6356, 0.3067]], grad_fn=<ThAddmmBackward>)

In [24]:
L2.parameters

<bound method Module.parameters of Linear(in_features=5, out_features=2, bias=True)>

In [25]:
L2.bias

Parameter containing:
tensor([-0.1980, -0.2490], requires_grad=True)

In [26]:
sample_data = Variable(torch.Tensor([[1, 2, -1, -1]]))

In [27]:
class RELU():
    def __init__(self, vec = None):
        if(vec is not None):
            self.vec = vec
    def relu(self):
        

SyntaxError: unexpected EOF while parsing (<ipython-input-27-ac656317b274>, line 6)

In [28]:
myObj = RELU(torch.Tensor([1, 2, -1, -1]))

NameError: name 'RELU' is not defined

In [29]:
myObj.relu()

NameError: name 'myObj' is not defined

In [30]:
sample_vec = torch.Tensor([[1, 2, -1, -1]])

## Creating our first network

In [31]:
import torch.nn as nn

In [32]:
class FirstNetwork(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(FirstNetwork, self).__init__()
        self.layer1 = nn.Linear(input_size, hidden_size)
        self.layer2 = nn.Linear(hidden_size, output_size)
    def __forward__(self, input):
        out = self.layer1(input)
        out = nn.ReLU(out)
        out = self.layer2(out)
        return out
    

## Loss Functions

**Mean Square Error** Loss Function

In [34]:
loss = nn.MSELoss()
input_ = Variable(torch.randn(3, 5), requires_grad=True)
target = Variable(torch.randn(3, 5))
output = loss(input_, target)
output.backward()

In [35]:
def cross_entropy(true_label, prediction):
    if(true_label == 1):
        return -np.log(prediction)
    else:
        return -np.log(1-prediction)

In [37]:
loss = nn.CrossEntropyLoss()
input_ = Variable(torch.randn(3, 5), requires_grad=True)
output = Variable(torch.LongTensor(3).random_(5))
l = loss(input_, output)
l.backward()

## Loss Functions and Their Usage

1. L1 Loss - Generally used for regularizer. 
2. MSE Loss - For regression problems.
3. Cross-Entropy Loss - For binary and multi class classification problems.
4. NLL Loss - For classification problems, allows to use specific weights to handle imbalanced results.
5. NLL Loss2d 

Source: Deep Learning with PyTorch